import db from "../db";

/* Populate Meme_has_caption */
try {
    db.serialize(() => {
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [1, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [1, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [1, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [2, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [2, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [2, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [3, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [3, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [3, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [4, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [4, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [4, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [5, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [5, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [5, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [6, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [6, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [6, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [6, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [7, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [7, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [7, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [8, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [8, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [8, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [9, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [9, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [9, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [10, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [10, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [10, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [10, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [10, 'steve_carrel']);

        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [11, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [11, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [11, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [12, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [12, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [12, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [13, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [13, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [13, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [14, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [14, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [14, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [15, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [15, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [15, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [15, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [16, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [16, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [16, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [17, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [17, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [17, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [17, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [18, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [18, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [18, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [19, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [19, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [19, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [20, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [20, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [20, 'giveup_rain']);

        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [21, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [21, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [21, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [22, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [22, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [22, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [23, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [23, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [23, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [24, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [24, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [24, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [25, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [25, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [25, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [26, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [26, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [26, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [27, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [27, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [27, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [28, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [28, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [28, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [29, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [29, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [29, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [30, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [30, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [30, 'veins']);

        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [31, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [31, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [31, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [32, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [32, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [32, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [33, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [33, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [33, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [34, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [34, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [34, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [35, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [35, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [35, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [36, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [36, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [36, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [37, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [37, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [37, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [38, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [38, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [38, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [39, 'bugs_bunny_shoot']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [39, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [39, 'giveup_rain']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [40, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [40, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [40, 'bugs_bunny_shoot']);

        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [41, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [41, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [41, 'steve_carrel']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [42, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [42, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [42, 'veins']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [43, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [43, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [43, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [44, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [44, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [44, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [45, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [45, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [45, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [46, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [46, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [46, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [47, 'boii']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [47, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [47, 'creep']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [48, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [48, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [48, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [49, 'seal_good']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [49, 'christian_bale']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [49, 'steve_harvey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [50, 'monkey_puppet']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [50, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [50, 'giveup_rain']);

        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [51, 'persian_monkey']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [51, 'seal_weird']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [51, 'patrick']);
        db.run(`INSERT INTO meme_has_caption (caption_id, meme_name) VALUES (?, ?)`, [51, 'monkey_puppet']);

        console.log('meme_has_caption populated')
    });
} catch (error) {
    console.log("Error in populating meme_has_caption")
    console.log(error);
}
